# -*- coding: utf-8 -*-
"""Unified entry point for the organized C-problem submission project.

The project is arranged by problem for final submission, but the original
solvers still share common modules and write runtime outputs to central
directories. This wrapper prepares import paths, invokes the selected workflow,
and synchronizes generated outputs back to the corresponding problem folders.
"""

from __future__ import annotations
try:
    from bootstrap_paths import configure_paths as _configure_organized_paths
except ModuleNotFoundError:
    import sys as _organized_sys
    from pathlib import Path as _OrganizedPath
    _organized_root = next((p for p in _OrganizedPath(__file__).resolve().parents if (p / "00_common_core").is_dir()), None)
    if _organized_root is not None:
        _organized_sys.path.insert(0, str(_organized_root))
    from bootstrap_paths import configure_paths as _configure_organized_paths
_configure_organized_paths(__file__)

import argparse

from bootstrap_paths import configure_paths


ROOT = configure_paths(__file__)


def check_imports() -> None:
    """Verify that all core modules can be imported from the organized layout."""
    import data_config
    import geometry
    import packing
    import routing
    import optimizer
    import validator
    import q1_solver
    import q2_solver
    import q3_solver
    import audit

    modules = [
        data_config,
        geometry,
        packing,
        routing,
        optimizer,
        validator,
        q1_solver,
        q2_solver,
        q3_solver,
        audit,
    ]
    for module in modules:
        print(f"OK import {module.__name__}: {getattr(module, '__file__', '')}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run or validate the organized C-problem project.")
    parser.add_argument("--check-imports", action="store_true", help="only check organized imports")
    parser.add_argument("--second-stage", action="store_true", help="run second-stage optimization instead of main")
    args = parser.parse_args()

    if args.check_imports:
        check_imports()
        return 0

    if args.second_stage:
        from run_second_stage_optimization import main as run_second_stage

        code = run_second_stage()
    else:
        from main import main as run_main

        code = run_main()

    from sync_outputs import sync_outputs

    # Keep the readable per-question folders consistent with central runtime
    # outputs generated by the original solver modules.
    sync_outputs()
    return code


if __name__ == "__main__":
    raise SystemExit(main())

